---
- name: find ip address
  hosts: nk1
  gather_facts: false      
  tasks:
    - name: Formatting the mac address
      set_fact:
        mactemp: "{{ mac | replace('.','') | replace(':','') | replace('-','') }}"
      when: mac | length > 4

    - name: show mac address
      debug:
        msg: "{{ mactemp }}"

    - name: Formatting the Mac address
      set_fact:
        mac: " {{ mactemp[0:4] }}.{{mactemp[4:8]}}.{{mactemp[8:12]}}"
      when: mac | length > 4

    - name: show mac address
      debug:
        msg: "{{ mac }}"


    - name: Convert Mac address to lowercase
      set_fact:
        mac: "{{mac | lower }}"

    - name: "Nexus: show ip arp | inc {{mac}}"
      cisco.nxos.nxos_command:
        commands: show ip arp | inc {{mac}}
      register: arp

    - name: Printing the arp output
      debug:
        msg: "{{ arp.stdout_lines[0] }}"