---
- name: find ip address
  hosts: nk1
  gather_facts: false      
  tasks:
    - name: Formatting the mac address
      update_fact:
        mac: "{{ mac | replace('.','') | replace(':','') | replace('-','') }}"
      when: mac | length > 4

    - name: Formatting the Mac address
      update_fact:
        mac: "{{ mac[0:4] }}.{{mac[4:8]}}.{{mac[8:12]}}"
      when: mac | length > 4

    - name: Convert Mac address to lowercase
      update_fact:
        mac: "{{ mac | lower }}"

    - name: "Nexus: show ip arp | inc {{mac}}"
      cisco.nxos.nxos_command:
        commands: show ip arp | inc {{mac}}
      register: arp

    - name: Printing the arp output
      debug:
        msg: "{{ arp.stdout_lines[0] }}"