---
- name: find ip address
  hosts: nk1
  gather_facts: false      
  tasks:
    - name: Formatting the mac address
      ansible.utils.update_fact:
        updates:
        - path: mac
          value : "{{ mac | replace('.','') | replace(':','') | replace('-','') }}"
      when: mac | length > 4

    - name: Formatting the Mac address
      ansible.utils.update_fact:
       updates:
        - path: mac
          value : "{{ mac[0:4] }}.{{mac[4:8]}}.{{mac[8:12]}}"
      when: mac | length > 4

    - name: Convert Mac address to lowercase
      ansible.utils.update_fact:    
       updates:
        - path: mac
          value : "{{ mac | lower }}"
        

    - name: "Nexus: show ip arp | inc {{mac}}"
      cisco.nxos.nxos_command:
        commands: show ip arp | inc {{mac}}
      register: arp

    - name: Printing the arp output
      debug:
        msg: "{{ arp.stdout_lines[0] }}"