---
- name: Lookup NAT information for Ochsner Connection
  hosts: ASR2
  gather_facts: false      
  tasks:
    - name: "Locating the Nat information"
      cisco.ios.ios_command:
        commands: show run | include ^ip nat.+{{ipaddress}}
      register: output

    - name: Parse IP address
      set_fact:    
        NATIP : "{{ output.stdout[0] | regex_findall('([0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}) (147.206.97.[0-9]{1,3}))') }}"
               

    - name: Here is the NAT information
      debug:
        msg: "{{ NATIP | default('NOT FOUND') }}"  