---
- name: find ip address
  hosts: WLC9800 
  gather_facts: false      
  tasks:
    - name: "GETTING A LIST OF AP'S FROM THE CONTROLLER"
      cisco.ios.ios_command:
        commands: show ap tag summary | inc default-site-tag
      register: apData    

    - set_fact:
      apName : "{{ apData |  regex_findall('AP[0-9A-Fa-f]{4}.[0-9A-Fa-f]{4}.[0-9A-Fa-f]{4}') }}"

    - name: Printing the arp output
      debug:
        msg: "{{ apName }}"